### ISSUE TITLE
UI Test

### ISSUE THREAD

**Issue by jedsada-gh** [jangrewe/gitlab-ci-android#11]
How to create emulator?

**Comment by jangrewe** [comment]
https://developer.android.com/studio/tools/help/android.html

**Comment by jedsada-gh** [comment]
Sorry, I used 
functionalTests:
  stage: test
  script:
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    - echo y | tools/android --silent update sdk --no-ui --all --filter sys-img-x86-google_apis-25
    - echo no | tools/android create avd -n test -t android-25 --abi google_apis/x86
    - tools/emulator64-x86 -avd test -no-window -no-audio &
    - ./android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew connectedStagingDebugAndroidTest
  artifacts:
    paths:
    - app/build/reports/androidTests/

Error : /bin/bash: line 50: tools/android: No such file or directory

Can you help me please, Thank.
