### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wldhx** [jangrewe/gitlab-ci-android#12]
Would you mind adding something like MIT to this repo? I'd like to fork it and make it work with GL container registry (okay, TBH, I already did, but I'd like to open-source it too), but technically, without license, it's protected by copyright.

**Comment by jangrewe** [comment]
Sure, MIT License has been added! =)

**Comment by wldhx** [comment]
Thanks!

For reference, the project: https://gitlab.com/motorica-org/gitlab-ci-android. I also refactored the Dockerfile somewhat (like removing the unnecessary anymore workaround for java certificates), so perhaps you'll want to take a look ;)

**Comment by jangrewe** [comment]
Thanks for the hint, i'll test it out! =)
