### ISSUE TITLE
gradlew not found

### ISSUE THREAD

**Issue by ardevd** [jangrewe/gitlab-ci-android#13]
Im getting the following error: 

```
Successfully extracted cache
$ export GRADLE_USER_HOME=$(pwd)/.gradle
$ chmod +x ./gradlew
chmod: cannot access './gradlew': No such file or directory
ERROR: Build failed: exit code 1
```

Any idea whats causing this?

**Comment by jangrewe** [comment]
Hi, that means you don't have the Gradle wrapper script `gradlew` in your repo's root directory, which should be the default for Android Studio projects.

This is an issue with your Android Studio project, not with the Docker image.
