### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by MyWay** [jangrewe/gitlab-ci-android#14]
Hello,
at some point I'm getting:
transformClassesWithPreJackRuntimeLibrariesForDebug
"ERROR: Build failed (system failure): Get https://ip:port/v1.18/containers/716cd1414d69221bdc8d317351aa113adf30b1bdb14273541f8293534c97c460/json: net/http: TLS handshake timeout"

Any idea of the reason?

**Comment by jangrewe** [comment]
Hi, that doesn't look like it's an issue with the container, but rather your GitLab. Could you post a longer log excerpt, preferably the whole thing (you can of course remove the majority of the lines generated by your script).

**Comment by MyWay** [comment]
Yes,
this is the script:
`image: jangrewe/gitlab-ci-android

stages:
- build
- test

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
- if [ ! -d "/cache$ANDROID_HOME" ]; then mv $ANDROID_HOME /cache$ANDROID_HOME; fi
- export ANDROID_HOME=/cache$ANDROID_HOME

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/app-debug.apk
  environment: debug

unitTests:
  stage: test
  script:
    - ./gradlew test
`

and this is the entire output cleaned:
`[0KRunning with gitlab-ci-multi-runner 1.10.4 (b32125f)[0;m
[0;m[0KUsing Docker executor with image jangrewe/gitlab-ci-android ...
[0;m[0KPulling docker image jangrewe/gitlab-ci-android ...
[0;mRunning on runner-fa6cab46-project-364517-concurrent-0 via runner-fa6cab46-machine-1486586479-3661eb25-gce...
[32;1mCloning repository...[0;m
Cloning into '/builds/myusername/myApp'...
[32;1mChecking out c92d72d9 as master...[0;m
[32;1mSkipping Git submodules setup[0;m
[32;1mChecking cache for 364517...[0;m
[32;1mSuccessfully extracted cache[0;m
[32;1m$ export GRADLE_USER_HOME=$(pwd)/.gradle[0;m
[32;1m$ chmod +x ./gradlew[0;m
[32;1m$ if [ ! -d "/cache$ANDROID_HOME" ]; then mv $ANDROID_HOME /cache$ANDROID_HOME; fi[0;m
[32;1m$ export ANDROID_HOME=/cache$ANDROID_HOME[0;m
[32;1m$ ./gradlew assembleDebug[0;m
Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /builds/myusername/myApp/.gradle/wrapper/dists/gradle-2.14.1-all/4cj8p00t3e5ni9e8iofg8ghvk7/gradle-2.14.1-all.zip to /builds/myusername/myApp/.gradle/wrapper/dists/gradle-2.14.1-all/4cj8p00t3e5ni9e8iofg8ghvk7
Set executable permissions for: /builds/myusername/myApp/.gradle/wrapper/dists/gradle-2.14.1-all/4cj8p00t3e5ni9e8iofg8ghvk7/gradle-2.14.1/bin/gradle
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Download...
....
:myApp:preBuild UP-TO-DATE
:myApp:preDebugBuild UP-TO-DATE
:myApp:compileDebugNdk UP-TO-DATE
:myApp:checkDebugManifest
:myApp:extractProguardFiles
:myApp:preReleaseBuild
:myApp:prepareComAndroidSupportAnimatedVectorDrawable2510Library
:myApp:prepareComAndroidSupportAppcompatV72510Library
:myApp:prepareComAndroidSupportDesign2510Library
:myApp:preDebugAndroidTestBuild UP-TO-DATE
:myApp:prepareComAndroidSupportMultidex101Library
:myApp:prepareComAndroidSupportRecyclerviewV72510Library
:myApp:prepareComAndroidSupportSupportCompat2510Library
:myApp:prepareComAndroidSupportSupportCoreUi2510Library
:myApp:prepareComAndroidSupportSupportCoreUtils2510Library
:myApp:prepareComAndroidSupportSupportFragment2510Library
:myApp:prepareComAndroidSupportSupportMediaCompat2510Library
:myApp:prepareComAndroidSupportSupportV42510Library
:myApp:prepareComAndroidSupportSupportVectorDrawable2510Library
:myApp:prepareComAndroidSupportTransition2510Library
:myApp:prepareComCommonswareCwacPager024Library
:myApp:prepareComGithubNispokSnackbarV2109Library
:myApp:prepareComGithubPaolorotoloAppintro340Library
:myApp:prepareComGoogleAndroidGmsPlayServicesAds940Library
:myApp:prepareComGoogleAndroidGmsPlayServicesAdsLite940Library
:myApp:prepareComGoogleAndroidGmsPlayServicesBase940Library
:myApp:prepareComGoogleAndroidGmsPlayServicesBasement940Library
:myApp:prepareComGoogleAndroidGmsPlayServicesClearcut940Library
:myApp:prepareComGoogleAndroidGmsPlayServicesGass940Library
:myApp:prepareComGoogleAndroidGmsPlayServicesTasks940Library
:myApp:prepareComGoogleFirebaseFirebaseAds940Library
:myApp:prepareComGoogleFirebaseFirebaseAnalytics940Library
:myApp:prepareComGoogleFirebaseFirebaseAnalyticsImpl940Library
:myApp:prepareComGoogleFirebaseFirebaseCommon940Library
:myApp:prepareComGoogleFirebaseFirebaseCore921Library
:myApp:prepareComGoogleFirebaseFirebaseCrash940Library
:myApp:prepareComGoogleFirebaseFirebaseIid940Library
:myApp:prepareComSquareupLeakcanaryLeakcanaryAndroid14Library
:myApp:prepareDeCkettiLibraryChangelogCkchangelog121Library
:myApp:prepareDebugDependencies
:myApp:compileDebugAidl
:myApp:compileDebugRenderscript
:myApp:generateDebugBuildConfig
:myApp:generateDebugResValues
:myApp:processDebugGoogleServices
Parsing json file: /builds/myusername/myApp/myApp/google-services.json
:myApp:generateDebugResources
:myApp:mergeDebugResources
:myApp:processDebugManifest
:myApp:processDebugResources
:myApp:generateDebugSources
:myApp:unzipJacocoAgent
:myApp:transformClassesWithPreJackPackagedLibrariesForDebug
:myApp:transformClassesWithPreJackRuntimeLibrariesForDebug
:myApp:processDebugJavaRes UP-TO-DATE
:myApp:transformResourcesWithMergeJavaResForDebug
:myApp:transformJackWithJackForDebug
Unable to find coverage plugin '/cache/sdk/build-tools/25.0.2/jack-coverage-plugin.jar'.  Disabling code coverage.
Incremental mode is disabled due to multi-dex legacy mode
[31;1mERROR: Build failed (system failure): Get https://35.185.11.139:2376/v1.18/containers/e433a162822b7d61f122c3ee51d54635ac8fe28e64df5411ff577cae4bc21201/json: net/http: TLS handshake timeout
[0;m`

**Comment by jangrewe** [comment]
Yup, not a problem with my image, but rather with whatever you're running it on.
That URL seems to be a Google Cloud Engine box, and there's a timeout talking to it...
I'm also pretty sure that it would fail even if there was no timeout, as you're talking to an IP address via HTTPS, and that certificate is only valid for `unknown.runner-72989761-machine-1486587819-12c6b8e4-gce`, which doesn't match the "hostname" that is the IP.
