### ISSUE TITLE
ndk support?

### ISSUE THREAD

**Issue by DavidMont** [jangrewe/gitlab-ci-android#15]
ndk support? If possible can u add ndk support?

**Comment by jangrewe** [comment]
The image is still building, but the NDK should be included now!

**Comment by jangrewe** [comment]
Sorry, i had to remove the NDK again, as it increased the image size to over 4GB. But feel free to either install it during your CI job, or fork my repo and add it yourself! 🙂

**Comment by ardevd** [comment]
Could you elaborate on this? I'm not too familar with gitlab CI but how would I add the NDK?

**Comment by jangrewe** [comment]
You can run something like this:
```
${ANDROID_HOME}/cmdline-tools/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} <ndk-package-name>
```
