### ISSUE TITLE
Replace Ubuntu with Alpine

### ISSUE THREAD

**Issue by Bmooij** [jangrewe/gitlab-ci-android#33]
I do not have enough knowledge of docker (yet).
But I saw in a other repo that Alpine was used, instead of ubuntu.
[min-alpine-android-sdk](https://github.com/tabrindle/min-alpine-android-sdk) 

This reduces the size of the container.

Is it possible to replace:
`FROM ubuntu:17.04`
with
`FROM frolvlad/alpine-oraclejdk8:full`

Thank you!

**Comment by vararg** [comment]
True, it would be useful update.

**Comment by benjohnde** [comment]
We currently use one:

https://github.com/Preventis/docker-android-alpine

Maybe this helps :)

**Comment by jangrewe** [comment]
Alpine is great, but unfortunately can cause issues with code that needs the proper libc, and musl is not always an option. For fully self-contained jobs this may be fine, but i prefer compatibility over size.
