### ISSUE TITLE
pull docker fail

### ISSUE THREAD

**Issue by quhuainan** [jangrewe/gitlab-ci-android#40]
I always get the error that it is "Using Docker executor with image jangrewe/gitlab-ci-android ...
ERROR: Preparation failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"。

**Comment by jangrewe** [comment]
Please fix your setup, this is not an issue of the image.

**Comment by quhuainan** [comment]
OK，thank you!
