### ISSUE TITLE
Error: No such image: jangrewe/gitlab-ci-android

### ISSUE THREAD

**Issue by Taharo** [jangrewe/gitlab-ci-android#41]
Pull image error

Log:
![image](https://user-images.githubusercontent.com/16466944/40185098-7e507122-59fa-11e8-847d-6be7a5d0501a.png)

Using Docker executor with image jangrewe/gitlab-ci-android ...
Pulling docker image jangrewe/gitlab-ci-android ...
ERROR: Preparation failed: Error: No such image: jangrewe/gitlab-ci-android
Will be retried in 3s ...
Using Docker executor with image jangrewe/gitlab-ci-android ...
Pulling docker image jangrewe/gitlab-ci-android ...
ERROR: Preparation failed: Error: No such image: jangrewe/gitlab-ci-android
Will be retried in 3s ...
Using Docker executor with image jangrewe/gitlab-ci-android ...
Pulling docker image jangrewe/gitlab-ci-android ...
ERROR: Preparation failed: Error: No such image: jangrewe/gitlab-ci-android
Will be retried in 3s ...
ERROR: Job failed (system failure): Error: No such image: jangrewe/gitlab-ci-android

**Comment by jangrewe** [comment]
Can't reproduce, check your system (wrong default registry?).
```
$ docker pull jangrewe/gitlab-ci-android
Using default tag: latest
latest: Pulling from jangrewe/gitlab-ci-android
18c8f805be45: Downloading [=================================>                 ]  26.96MB/39.98MB
f7869fb3b98c: Download complete 
f75000414ffb: Download complete 
c27c5092058d: Download complete 
add65c7404ea: Download complete 
424a33f1aa7d: Downloading [============================>                      ]  91.52MB/159.1MB
d7a69f895890: Download complete 
53579735c0d1: Downloading [====================================>              ]  98.56MB/136.2MB
7c7be9199868: Waiting 
489f7a489e7f: Waiting 
76fe275dfaef: Waiting 
4fbd58bdc0e5: Waiting 
73ffa91f64f6: Waiting 
^C
```
