### ISSUE TITLE
Update build-tools to 30.0.0

### ISSUE THREAD

**Issue by SaeedZhiany** [jangrewe/gitlab-ci-android#51]
Is it possible to add a new docker with build-tools v30.0.0, please?

Thanks

**Comment by jangrewe** [comment]
I don't think there's a final release for 30.0.0 out yet, only RC4?

**Comment by SaeedZhiany** [comment]
no, already there is one. I guess it has been released yesterday as final (stable) release.

**Comment by jangrewe** [comment]
updated! please allow some time for Docker Hub to build a new image
