### ISSUE TITLE
Pass txt file to sdkmanager 

### ISSUE THREAD

**Issue by cbhramar** [jangrewe/gitlab-ci-android#61]
Hi @jangrewe!

Can we use the `--package_file` argument (https://developer.android.com/studio/command-line/sdkmanager#install_packages) to point to packages.txt? That'll eliminate manual text processing to install the packages.

Thanks!

**Comment by jangrewe** [comment]
Hi, i can't remember if this didn't work as expected or previously didn't exist and is a new feature, but i'll try it out.

**Comment by jangrewe** [comment]
It used to be broken: https://github.com/jangrewe/gitlab-ci-android/issues/23
... but now it works again, so i'll be using it again.
