### ISSUE TITLE
Invalid gitlab-ci.yml example

### ISSUE THREAD

**Issue by marzn** [jangrewe/gitlab-ci-android#7]
Gitlab CI Lint tells:
Status: syntax is incorrect
Error: build job: stage parameter should be build 

Adding `stage: build` fixes this.

```
...
build:
  stage: build
  script:
  - ./gradlew assembleDebug
...
```

Thanks for your docker img 👍

**Comment by jangrewe** [comment]
oops, thanks for noticing, i've fixed the README =)
