### ISSUE TITLE
Add supporting Android NDK

### ISSUE THREAD

**Issue by Paniker123** [jangrewe/gitlab-ci-android#71]
Could you please add supporting android NDK into the image?

**Comment by halohoop** [comment]
Require NDK, too.

**Comment by halohoop** [comment]
FYI: https://developer.android.com/studio/command-line/sdkmanager?hl=zh-cn

**Comment by jangrewe** [comment]
Please see https://github.com/jangrewe/gitlab-ci-android/issues/15
