### ISSUE TITLE
bad interpreter: Permission denied

### ISSUE THREAD

**Issue by DikenMaharjan** [jangrewe/gitlab-ci-android#73]
This is my .gitlab-ci.yml script:

![image](https://user-images.githubusercontent.com/75777392/159691476-7f687dcc-b682-4a4b-9df5-620ae64aec46.png)

The error is 
/bin/bash: ./gradlew: /usr/bin/: bad interpreter: Permission denied/bin/bash: ./gradlew: /usr/bin/: bad interpreter: Permission denied

![image](https://user-images.githubusercontent.com/75777392/159691232-75e9ef40-d92c-4505-9956-10093db4410a.png)

**Comment by jangrewe** [comment]
Please report this to whoever provides the `seanghay/android-ci` image you are using - which is definitely not me.

**Comment by DikenMaharjan** [comment]
oh okay. Thanks a lot.

**Comment by DikenMaharjan** [comment]
Could the problem be due to version issues? The title for seanghay/android-ci is  "Docker Image of Android CI for API 29".
I am using compileSdk 31 and targetSdk 31.

**Comment by jangrewe** [comment]
No, you'll get those problems later, when Gradle finds out about them.
