### ISSUE TITLE
How to make use of settings.xml for private repos

### ISSUE THREAD

**Issue by geri-m** [jangrewe/gitlab-ci-android#8]
I integrated the Docker Image into my gitlab for building Android apps, which works great. But I'm unable to "teach" the container to look for dependencies in a dedicated Nexus. I already extended the image by adding the settings.xml (ADD ./settings.xml /root/.m2/settings.xml), but during the gradle build the settings.xml is not used.

Even if I pass the settings.xml to the gradlew build (./gradlew -Pmaven.settings.location=/root/.m2/settings.xml assemble), gradle does not use it. I don't want to specified the repos (+ credentials) in my gradle.build files. 

Any help is appreciated.

**Comment by jangrewe** [comment]
Sorry, i'm not much of a Maven pro, so i wouldn't be of much help.
You could run the Docker image outside of a CI job with an interactive shell and try to figure out where mvn expects its file, though?
